// Smorfia napoletana tradizionale — numero → soggetto.
// Global non-module perché l'app deve girare anche via `file://` (doppio-click),
// dove ES modules sono bloccati da CORS nei browser più restrittivi.
window.SMORFIA = {
  1: "L'Italia",
  2: "'A piccerella",
  3: "'A jatta",
  4: "'O puorco",
  5: "'A mana",
  6: "Chella che guarda 'nterra",
  7: "'O vasetto",
  8: "'A Madonna",
  9: "'A figliata",
  10: "'E fasule",
  11: "'E suricille",
  12: "'E surdate",
  13: "Sant'Antonio",
  14: "'O 'mbriaco",
  15: "'O guaglione",
  16: "'O culo",
  17: "'A disgrazia",
  18: "'O sanghe",
  19: "'A resata",
  20: "'A festa",
  21: "'A femmena annura",
  22: "'O pazzo",
  23: "'O scemo",
  24: "'E guardie",
  25: "Natale",
  26: "Nanninella",
  27: "'O cantero",
  28: "'E zizze",
  29: "'O pate d'e criature",
  30: "'E ppalle d'o tenente",
  31: "'O padrone 'e casa",
  32: "'O capitone",
  33: "L'anne 'e Cristo",
  34: "'A capa",
  35: "'O cucchiello",
  36: "'E castagnelle",
  37: "'O mmunaco",
  38: "'E mmazzate",
  39: "'A funa 'n cànna",
  40: "'A paposcia",
  41: "'O curtiello",
  42: "'O ccafè",
  43: "'Onna pereta fore 'o balcone",
  44: "'E ccancelle",
  45: "'O vino bbuono",
  46: "'E denare",
  47: "'O muorto",
  48: "'O muorto che pparla",
  49: "'O piezzo 'e carne",
  50: "'O ppane",
  51: "'O ciardino",
  52: "'A mamma",
  53: "'O viecchio",
  54: "'O cappiello",
  55: "'A museca",
  56: "'A caruta",
  57: "'O scartellato",
  58: "'O paccotto",
  59: "'E pile",
  60: "Se lamenta",
  61: "'O cacciatore",
  62: "'O muorto acciso",
  63: "'A sposa",
  64: "'A sciammeria",
  65: "'O chianto",
  66: "'E ddoje zetelle",
  67: "'O totaro dint'a chitarra",
  68: "'A zuppa cotta",
  69: "Sotto 'ncoppa e 'ncoppa sotto",
  70: "'O palazzo",
  71: "L'ommo 'e mmerda",
  72: "'A maraviglia",
  73: "'O spitale",
  74: "'A rotta",
  75: "Pulecenella",
  76: "'A funtana",
  77: "'E riavulille",
  78: "'A bella figliola",
  79: "'O mariuolo",
  80: "'A vocca",
  81: "'E sciure",
  82: "'A tavula 'mparata",
  83: "'O maletiempo",
  84: "'A cchiesa",
  85: "L'anema d'o priatorio",
  86: "'A puteca",
  87: "'E perucchie",
  88: "'E casecavalle",
  89: "'A vecchia",
  90: "'A paura",
};
